language: ruby
rvm:
  - 2.1.1
before_install:
  - gem up --system
  - gem up -N
  - gem install -N bundler
  - bundle update
  - npm -g up npm
  - npm -g ins grunt-cli bower
  - npm -g up
  - npm install
  - bower install
script:
  - grunt
